## Numpy

In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
matrix[0]

array([1, 2, 3])

In [7]:
type(matrix[0][0])  # Numpy独自のデータタイプであり、intでないことに注意！

numpy.int64

In [8]:
# データタイプの指定が可能
# unsigned: + や - がないもので、integer で 8bit => 0~255 のinteger（画像などでもよく使う）
ndarray = np.array([1, 2, 3], dtype=np.uint8)  

In [9]:
ndarray

array([1, 2, 3], dtype=uint8)

In [10]:
# float32: 機械学習でデータを保存する際によく使う（容量節約）
ndarray2 = np.array([1, 2, 3], dtype=np.float32)  

# float64はメモリを倍確保できるので保存には向かず、実際に機械学習で学習する際に使う

In [11]:
# astype(): データタイプを変更
print(type(ndarray2[0]))
ndarray2.astype(np.uint8)

<class 'numpy.float32'>


array([1, 2, 3], dtype=uint8)

In [12]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
array3 = np.array([1, 2, 3])

In [18]:
array1 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [19]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
import numpy as np

a = np.array([[1,3], [4, 8]])
a

array([[1, 3],
       [4, 8]])

In [21]:
b = 1 + a[0][1]
print(b, type(b))
print(type(int(b)))
print(b)

c = 1
d = c + a[1][1]
print(d, type(d))
e = d + int(c)
print(e, type(e))

4 <class 'numpy.int64'>
<class 'int'>
4
9 <class 'numpy.int64'>
10 <class 'numpy.int64'>


In [22]:
z = np.array([[1, 2, 3, 10], [4, 5, 6, 20], [7, 8, 9, 30]])
z += 1
z + np.array([10, 20, 30, 40])

array([[12, 23, 34, 51],
       [15, 26, 37, 61],
       [18, 29, 40, 71]])

In [23]:
#z + np.array([[10, 20], [10, 10]])

In [24]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
ndarray.shape

(3, 2)

In [26]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [28]:
print(ndarray1.shape)

(3,)


In [29]:
print(ndarray2.shape)

(1, 3)


In [30]:
expand_ndarray = np.expand_dims(ndarray1, axis=0)
print(expand_ndarray)

[[1 2 3]]


In [31]:
expand_ndarray.shape

(1, 3)

In [32]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [33]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [34]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
ndarray = np.array([1, 2, 3, 4])

In [36]:
ndarray[-1]

4

In [37]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
ndarray[0, 1]

2

In [39]:
ndarray = np.array([1, 2, 3, 4])

In [40]:
ndarray[-3:3]

array([2, 3])

In [41]:
ndarray[:3]

array([1, 2, 3])

In [42]:
ndarray[-2:]

array([3, 4])

In [43]:
ndarray[:]

array([1, 2, 3, 4])

In [44]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [45]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [48]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

In [49]:
ndarray_practice = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
ndarray_practice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [50]:
ndarray_practice.shape

(5, 4)

In [51]:
# 6, 7, 10, 11, 14, 15 を取得したい場合
ndarray_practice[1:4, 1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [52]:
ndarray.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [53]:
expand_array = np.expand_dims(ndarray, axis=0)
expand_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [54]:
np.squeeze(expand_array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
np.squeeze

<function numpy.squeeze(a, axis=None)>

In [56]:
np.arange(3, 15, 2)

array([ 3,  5,  7,  9, 11, 13])

In [57]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [58]:
np.arange(29, 3, -1)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4])

In [59]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [60]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [61]:
np.logspace(0, 10, 5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [62]:
np.logspace(100, 1000, 10)

/opt/anaconda3/lib/python3.7/site-packages/numpy/core/function_base.py:274: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.e+100, 1.e+200, 1.e+300,     inf,     inf,     inf,     inf,
           inf,     inf,     inf])

In [63]:
np.linspace(10, 100, 10, endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [64]:
np.logspace(10, 100, 10, endpoint=False)

array([1.e+10, 1.e+19, 1.e+28, 1.e+37, 1.e+46, 1.e+55, 1.e+64, 1.e+73,
       1.e+82, 1.e+91])

In [65]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [66]:
np.zeros((5, 5), dtype=int, order='C')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
shape = (3, 5)
np.zeros(shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
shape = (5, 5)
np.ones(shape)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
np.ones((5, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [70]:
np.ones(2)

array([1., 1.])

In [71]:
np.ones((10, 5))*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [72]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [73]:
np.random.rand()

0.3933094260329154

In [74]:
np.random.rand()

0.31629835416632657

In [75]:
np.random.rand(3, 5)

array([[0.16822369, 0.84832877, 0.92991127, 0.69631535, 0.48369747],
       [0.19232867, 0.11741364, 0.30318808, 0.41671872, 0.49158995],
       [0.92253081, 0.25366197, 0.57641221, 0.30994261, 0.64173019]])

In [76]:
np.random.seed(1)
np.random.rand(2, 2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [77]:
np.random.rand()

0.14675589081711304

In [78]:
np.random.randn(3, 4)

array([[-1.10593508, -1.65451545, -2.3634686 ,  1.13534535],
       [-1.01701414,  0.63736181, -0.85990661,  1.77260763],
       [-1.11036305,  0.18121427,  0.56434487, -0.56651023]])

In [79]:
np.random.normal(10, 1)

10.729975596413844

In [80]:
np.random.randint(10, 100, (3, 3))

array([[70, 91, 18],
       [98, 23, 57],
       [82, 40, 81]])

In [81]:
np.random.randint(10)

3

In [82]:
a = [1, 2, 3]
np.random.choice(a)

3

In [83]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [84]:
np.random.choice(index_pool)

2

In [85]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [86]:
shape = (5, 5)
np.ones(shape)*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [87]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.random.randn(5, 5)

array([[ 0.37299379,  1.91382039,  0.33079713,  1.14194252, -1.12959516],
       [-0.85005238,  0.96082   , -0.21741818,  0.15851488,  0.87341823],
       [-0.11138337, -1.03803876, -1.00947983, -1.05825656,  0.65628408],
       [-0.06249159, -1.73865429,  0.103163  , -0.62166685,  0.27571804],
       [-1.09067489, -0.60998525,  0.30641238,  1.69182613, -0.74795374]])

In [89]:
np.random.normal(2, 2)

0.8384055534868156

In [90]:
np.random.normal(0, 1)

-0.11075397188900132

In [91]:
np.random.seed(1)
random_array = np.random.randint(10, 50, 10)
random_array

array([47, 22, 18, 19, 21, 15, 25, 10, 26, 11])

In [92]:
np.random.choice(random_array)

10

In [93]:
np.random.randint(10, 100, 5)

array([16, 35, 60, 30, 28])

In [94]:
np.random.randn(2, 2)

array([[-2.65426198,  1.15226492],
       [ 0.19664341, -1.54521415]])

In [95]:
np.random.normal(1, 1, (3, 3))

array([[0.91189591, 1.85223932, 1.67723401],
       [0.89312157, 1.72527406, 1.93488915],
       [2.11829698, 1.05561319, 1.37665664]])

In [96]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 0.37613502, -0.16419077, -0.08454345,  0.93155816,  1.70693497],
       [-0.89191376,  1.73559653, -0.63110833, -0.90734336,  0.37475197],
       [-0.47338275, -0.45452082, -0.08533806,  1.50318838,  1.16064112],
       [-0.4829414 , -1.80662901, -0.91544761, -0.06973398, -0.84995477],
       [ 0.05062323,  0.70507238, -1.67994195,  1.99997564,  1.15696327]])

In [97]:
std_norm.max()

1.9999756374163042

In [98]:
np.max(std_norm)

1.9999756374163042

In [99]:
std_norm.min()

-1.8066290099790856

In [100]:
np.min(std_norm)

-1.8066290099790856

In [101]:
std_norm.argmax()

23

In [102]:
std_norm.flatten()[23]

1.9999756374163042

In [103]:
std_norm.argmin()

16

In [104]:
ndarray = np.random.randint(10, 50, (3, 3))
ndarray

array([[38, 20, 42],
       [34, 33, 11],
       [23, 13, 10]])

In [105]:
ndarray.argmin(axis=1)

array([1, 2, 2])

In [106]:
np.argmax(ndarray, axis=0)

array([0, 1, 0])

In [107]:
std_norm.mean()

0.08817802587408956

In [108]:
np.mean(std_norm)

0.08817802587408956

In [109]:
np.median(std_norm)

-0.08454344833421344

In [110]:
np.median(ndarray)

23.0

In [112]:
import time

t_array = np.random.randn(10000, 10000)


def time_checker(func):
    def inner(*args, **kwargs):
        before = time.time()
        func(*args, **kwargs)
        after = time.time()
        print(f"{after - before:.4f}秒")
    return inner


@time_checker
def t_mean(array):
    np.mean(array)
    print("平均値を計算")


@time_checker
def t_median(array):
    np.median(array)
    print("中央値を計算")

    
t_mean(t_array)
t_median(t_array)

平均値を計算
0.0408秒
中央値を計算
1.5464秒


In [113]:
std_norm.std()

1.0334389178199466

In [114]:
np.std(std_norm)

1.0334389178199466

In [115]:
s = [1, 2, 3, 4, 5, 6, 7]
np.sqrt(s)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [116]:
np.log(100)

4.605170185988092

In [117]:
np.log(e)

2.302585092994046

In [119]:
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [120]:
np.log10(100)

2.0

In [121]:
np.exp(1)

2.718281828459045

In [122]:
np.e

2.718281828459045

In [123]:
np.sum(s)

28

In [124]:
np.sum(x)

55.0

In [126]:
array = np.arange(1, 11).reshape(2, 5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [127]:
np.sum(array, axis=0)

array([ 7,  9, 11, 13, 15])

In [128]:
np.sum(array, axis=1)

array([15, 40])

In [130]:
array = np.arange(-10, 0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [131]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

AttributeError: 'numpy.ndarray' object has no attribute 'abs'

In [133]:
np.nan

nan

In [134]:
type(np.nan)

float

In [135]:
a = None
a is None

True

In [136]:
np.isnan(np.log(-199))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

In [137]:
array = np.arange(10)
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [138]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [139]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [140]:
array[array>3]

array([4, 5, 6, 7, 8, 9])

In [141]:
type(np.where(array > 3))

tuple

In [143]:
ndarray = array.reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [144]:
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [146]:
(ndarray>3).all(axis=0)

array([False, False, False, False,  True])

In [148]:
(ndarray>3).any()

True

In [150]:
(ndarray>3).any(axis=1)

array([ True,  True])

In [151]:
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
np.unique(array)

array([1, 2, 3, 4, 5])

In [153]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

In [154]:
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

In [159]:
np.bincount([0, 1, 2, 3, 4, 5])

array([1, 1, 1, 1, 1, 1])

In [161]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [162]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [164]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [176]:
np.stack([ndarray_even, ndarray_odd], axis=-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [177]:
stacked_array = _

In [179]:
stacked_array.shape

(3, 3, 2)

In [223]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [225]:
s = _

In [226]:
s.shape

(2, 3, 3)

In [180]:
ndarray = np.random.randn(3, 4)
ndarray

array([[ 0.04767236,  0.66642984, -1.43604168, -0.86857661],
       [ 0.45538775, -0.51004391, -2.73003441,  0.36443481],
       [ 1.04115939,  0.14665889,  0.15787531,  1.80809173]])

In [182]:
np.transpose(ndarray)

array([[ 0.04767236,  0.45538775,  1.04115939],
       [ 0.66642984, -0.51004391,  0.14665889],
       [-1.43604168, -2.73003441,  0.15787531],
       [-0.86857661,  0.36443481,  1.80809173]])

In [183]:
transposed_ndarray = _
transposed_ndarray

array([[ 0.04767236,  0.45538775,  1.04115939],
       [ 0.66642984, -0.51004391,  0.14665889],
       [-1.43604168, -2.73003441,  0.15787531],
       [-0.86857661,  0.36443481,  1.80809173]])

In [184]:
transposed_ndarray.shape

(4, 3)

In [185]:
ndarray.T

array([[ 0.04767236,  0.45538775,  1.04115939],
       [ 0.66642984, -0.51004391,  0.14665889],
       [-1.43604168, -2.73003441,  0.15787531],
       [-0.86857661,  0.36443481,  1.80809173]])

In [186]:
ndarray

array([[ 0.04767236,  0.66642984, -1.43604168, -0.86857661],
       [ 0.45538775, -0.51004391, -2.73003441,  0.36443481],
       [ 1.04115939,  0.14665889,  0.15787531,  1.80809173]])

In [187]:
ndarray = np.random.normal(10, 2, (3, 4, 5))
ndarray

array([[[ 6.7922526 ,  8.0741053 , 11.29563545,  8.96861254,
         11.91623393],
        [ 8.48807791,  8.27717132, 11.33658242, 12.62800741,
          9.19062845],
        [11.89796198,  7.72508317, 11.69511173, 10.78657869,
         10.86986552],
        [12.5667322 ,  9.93404038,  5.56855528,  9.4227965 ,
          8.72790884]],

       [[ 6.63678018, 12.61715157, 12.19543174, 11.33557887,
         10.96755119],
        [ 9.89974065, 14.78697349, 11.68059901, 11.19890241,
         10.82283632],
        [10.446057  , 10.1244329 ,  8.31273918, 11.55382469,
          9.38780691],
        [10.72466408,  8.9944597 , 12.40295006, 10.02983407,
          8.65924718]],

       [[12.66719475,  9.26174396,  9.93386146, 11.65699386,
         11.29504746],
        [10.39394952, 14.00988066, 11.89639846, 10.21739249,
         12.6787394 ],
        [12.41326595, 11.2987101 ,  9.88940819, 14.4037706 ,
         11.39455211],
        [11.71573843, 10.53776265, 12.24579429,  9.51579869,
          6

In [188]:
ndarray.T.shape

(5, 4, 3)

In [189]:
ndarray = np.random.randn(3, 4, 5)
ndarray

array([[[-0.99850963,  0.29522105, -0.01886981, -1.55721949,
          0.61259994],
        [ 1.72657862,  0.07370237,  0.83772203,  0.47232469,
         -0.78773533],
        [-1.52485493,  0.0942979 , -0.53389093,  1.96692388,
          0.2759339 ],
        [ 0.21270239, -0.08179841,  0.6808429 ,  0.14586724,
          0.76807326]],

       [[-1.1401357 , -0.74767015, -0.44489364, -0.08578303,
          0.21585734],
        [ 0.52322417, -0.62687158,  1.23299659, -0.42901911,
          0.82970991],
        [-0.58638942, -0.5397725 ,  2.61701453, -1.0460464 ,
          1.10404702],
        [-1.87725673, -0.82364265,  1.91476758,  1.11609232,
          0.26360407]],

       [[ 0.22029171,  0.23342812, -0.15676526, -0.75410555,
         -1.25696782],
        [-0.24808868, -0.61943319, -2.10404179,  0.19438214,
         -0.65454206],
        [-1.26758317,  2.46974952, -0.05304614,  0.53566607,
         -0.51455747],
        [ 0.30452486, -0.70194345, -1.39930921, -0.82871117,
          1

In [190]:
np.save('sample_ndarray', ndarray)

In [192]:
np.load('sample_ndarray.npy')

array([[[-0.99850963,  0.29522105, -0.01886981, -1.55721949,
          0.61259994],
        [ 1.72657862,  0.07370237,  0.83772203,  0.47232469,
         -0.78773533],
        [-1.52485493,  0.0942979 , -0.53389093,  1.96692388,
          0.2759339 ],
        [ 0.21270239, -0.08179841,  0.6808429 ,  0.14586724,
          0.76807326]],

       [[-1.1401357 , -0.74767015, -0.44489364, -0.08578303,
          0.21585734],
        [ 0.52322417, -0.62687158,  1.23299659, -0.42901911,
          0.82970991],
        [-0.58638942, -0.5397725 ,  2.61701453, -1.0460464 ,
          1.10404702],
        [-1.87725673, -0.82364265,  1.91476758,  1.11609232,
          0.26360407]],

       [[ 0.22029171,  0.23342812, -0.15676526, -0.75410555,
         -1.25696782],
        [-0.24808868, -0.61943319, -2.10404179,  0.19438214,
         -0.65454206],
        [-1.26758317,  2.46974952, -0.05304614,  0.53566607,
         -0.51455747],
        [ 0.30452486, -0.70194345, -1.39930921, -0.82871117,
          1

In [193]:
dictionary = {
    'id': 1234,
    'image': ndarray
}

In [194]:
dictionary

{'id': 1234,
 'image': array([[[-0.99850963,  0.29522105, -0.01886981, -1.55721949,
           0.61259994],
         [ 1.72657862,  0.07370237,  0.83772203,  0.47232469,
          -0.78773533],
         [-1.52485493,  0.0942979 , -0.53389093,  1.96692388,
           0.2759339 ],
         [ 0.21270239, -0.08179841,  0.6808429 ,  0.14586724,
           0.76807326]],
 
        [[-1.1401357 , -0.74767015, -0.44489364, -0.08578303,
           0.21585734],
         [ 0.52322417, -0.62687158,  1.23299659, -0.42901911,
           0.82970991],
         [-0.58638942, -0.5397725 ,  2.61701453, -1.0460464 ,
           1.10404702],
         [-1.87725673, -0.82364265,  1.91476758,  1.11609232,
           0.26360407]],
 
        [[ 0.22029171,  0.23342812, -0.15676526, -0.75410555,
          -1.25696782],
         [-0.24808868, -0.61943319, -2.10404179,  0.19438214,
          -0.65454206],
         [-1.26758317,  2.46974952, -0.05304614,  0.53566607,
          -0.51455747],
         [ 0.30452486, -0.

In [195]:
np.save('sample_dict.npy', dictionary)

In [198]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)

In [202]:
type(loaded_dict[()])

dict

In [203]:
loaded_dict[()]

{'id': 1234,
 'image': array([[[-0.99850963,  0.29522105, -0.01886981, -1.55721949,
           0.61259994],
         [ 1.72657862,  0.07370237,  0.83772203,  0.47232469,
          -0.78773533],
         [-1.52485493,  0.0942979 , -0.53389093,  1.96692388,
           0.2759339 ],
         [ 0.21270239, -0.08179841,  0.6808429 ,  0.14586724,
           0.76807326]],
 
        [[-1.1401357 , -0.74767015, -0.44489364, -0.08578303,
           0.21585734],
         [ 0.52322417, -0.62687158,  1.23299659, -0.42901911,
           0.82970991],
         [-0.58638942, -0.5397725 ,  2.61701453, -1.0460464 ,
           1.10404702],
         [-1.87725673, -0.82364265,  1.91476758,  1.11609232,
           0.26360407]],
 
        [[ 0.22029171,  0.23342812, -0.15676526, -0.75410555,
          -1.25696782],
         [-0.24808868, -0.61943319, -2.10404179,  0.19438214,
          -0.65454206],
         [-1.26758317,  2.46974952, -0.05304614,  0.53566607,
          -0.51455747],
         [ 0.30452486, -0.

In [204]:
a = np.random.randn(3, 5)
a

array([[-1.94150169,  0.51809245, -0.26772978,  0.86851125, -0.54086578],
       [ 1.13548282,  1.89279833,  1.37996254, -0.41228971, -0.88308234],
       [ 0.53033664,  0.54415086,  1.85121207,  0.0992906 ,  0.6235021 ]])

In [207]:
b = np.array([1, 2, 4, 5])
a + b

ValueError: operands could not be broadcast together with shapes (3,5) (4,) 

In [215]:
np.exp(1)

2.718281828459045

In [216]:
np.e

2.718281828459045

In [222]:
np.log(2)

0.6931471805599453